/**
 * Domain types.
 *
 * These mirror `docs/api-contract.md` one to one. The backend agent and this file
 * must change together. Do not rename a field here without changing it there.
 */

/** A user as returned by every endpoint. The shape is identical everywhere. */
export type User = {
  id: string;
  username: string;
  email: string;
  displayName: string;
  avatarUrl: string | null;
  isOnline: boolean;
  lastSeenAt: string | null;
  createdAt: string;
};

/** The subset of a user that the UI actually renders. */
export type PublicUser = Omit<User, "email">;

export type ConversationType = "direct";

export type MessageStatus = "sent" | "read";

export type Message = {
  id: string;
  /** Generated by the sender's client. Used to reconcile the optimistic message. */
  clientId: string;
  conversationId: string;
  sender: User;
  body: string;
  createdAt: string;
  status: MessageStatus;
  readAt: string | null;
};

/**
 * What the message list renders.
 *
 * A message can exist in the UI before the backend has confirmed it, so the client
 * keeps two extra local states. The backend never sends these.
 */
export type MessageDelivery = "pending" | "sent" | "read" | "failed";

export type DisplayMessage = Message & {
  delivery: MessageDelivery;
  /** True while a POST is in flight, so the UI can avoid duplicate submits. */
  isSending: boolean;
};

export type Conversation = {
  id: string;
  type: ConversationType;
  /** The other user. Never the current user. */
  participant: User;
  lastMessage: Message | null;
  unreadCount: number;
  updatedAt: string;
};

export type MessagesPage = {
  messages: Message[];
  /** Opaque cursor for the next page. Null when the last page has been reached. */
  nextCursor: string | null;
};

export type AuthResponse = {
  user: User;
  accessToken: string;
  refreshToken: string;
};

export type RefreshResponse = {
  accessToken: string;
  refreshToken: string;
};

export type ConversationListResponse = {
  conversations: Conversation[];
};

export type UserSearchResponse = {
  users: User[];
};

/* -------------------------------------------------------------------------- */
/*                                  Auth input                                */
/* -------------------------------------------------------------------------- */

export type RegisterInput = {
  username: string;
  email: string;
  password: string;
  displayName: string;
};

export type LoginInput = {
  /** Accepts either a username or an email. */
  identifier: string;
  password: string;
};

export type UpdateProfileInput = {
  displayName?: string;
  avatarUrl?: string | null;
};

/* -------------------------------------------------------------------------- */
/*                              Realtime protocol                            */
/* -------------------------------------------------------------------------- */

/** Frames the client sends. */
export type ClientFrame =
  | { type: "auth"; payload: { token: string } }
  | { type: "typing"; payload: { conversationId: string; isTyping: boolean } }
  | { type: "read"; payload: { conversationId: string; messageId: string } }
  | { type: "ping"; payload: Record<string, never> };

/** Frames the server sends, one entry per frame type. */
export type ServerFramePayloads = {
  ready: { userId: string };
  "message:new": { message: Message };
  "message:updated": { message: Message };
  typing: { conversationId: string; userId: string; isTyping: boolean };
  presence: { userId: string; isOnline: boolean; lastSeenAt: string | null };
  read: { conversationId: string; userId: string; messageId: string; readAt: string };
  pong: Record<string, never>;
  error: { code: string; message: string };
};

export type ServerFrameType = keyof ServerFramePayloads;

/**
 * Derived from the payload map so a new frame type cannot be added in one place and
 * forgotten in the other.
 */
export type ServerFrame = {
  [K in ServerFrameType]: { type: K; payload: ServerFramePayloads[K] };
}[ServerFrameType];

export type SocketStatus = "idle" | "connecting" | "open" | "reconnecting" | "closed";
